# docker build -f Containerfile --no-cache  -t "caravanacloud/ecomarkets-app:0.0.1" .
# docker run -ti -p 3000:3000 "caravanacloud/ecomarkets-app:0.0.1"
# docker push "caravanacloud/ecomarkets-app:0.0.1"
FROM fedora:latest as build
RUN dnf -y install nodejs npm
WORKDIR /usr/src/svelte-app
COPY . .
RUN npm install
RUN npm run build

FROM fedora:latest as runtime
#RUN dnf -y --refresh update
RUN dnf -y install nodejs npm
RUN npm install -g serve
COPY --from=build /usr/src/svelte-app/build /opt/svelte-app/build
COPY --from=build /usr/src/svelte-app/package.json /opt/svelte-app/package.json
COPY --from=build /usr/src/svelte-app/node_modules /opt/svelte-app/node_modules

EXPOSE 3000
WORKDIR /opt/svelte-app/
# RUN find .
CMD ["node","build"]
