ARG VERSION=latest
FROM caravanacloud/ecomarkets-core-build:${VERSION} as build

RUN find "/home/container-user/"

FROM caravanacloud/ecomarkets-core-runtime:${VERSION}

COPY --from=build /home/container-user/ecomarkets/app /opt/ecomarkets/app

EXPOSE 9093
WORKDIR /opt/ecomarkets/app/

CMD ["serve","-s","build","-l","tcp://0.0.0.0:9093"]
