# podman build -f Containerfile --no-cache . -t ecomarkets-app:latest
# podman run -d -p 3000:3000 ecomarkets-app:latest
FROM fedora:latest as build
RUN dnf -y install nodejs npm
WORKDIR /usr/src/svelte-app
COPY . .
RUN npm install
RUN npm run build
RUN find .

FROM fedora:latest as runtime
RUN dnf -y update && dnf -y install nodejs npm
COPY --from=build /usr/src/svelte-app/build /opt/svelte-build
WORKDIR /opt
CMD ["node", "svelte-build"]
