# Build stage
ARG VERSION=latest
FROM caravanacloud/ecomarkets-core-build:${VERSION} as build

RUN find "/home/container-user/"

# Runtime stage
FROM caravanacloud/ecomarkets-core-runtime:${VERSION}

COPY --from=build --chown=container-user "/home/container-user/ecomarkets/web/target/ecomarkets-web-runner.jar" "/home/container-user/ecomarkets/web/target/web-runner.jar"
EXPOSE 9091

ARG JAVA_XARGS="-XX:InitialRAMPercentage=90.0"
ENTRYPOINT java $JAVA_XARGS -jar /home/container-user/ecomarkets/web/target/web-runner.jar
